
// WARNING: DO NOT EDIT THIS FILE.
// This file is automatically generated by the Zoom Indexer application
// and will be updated each time you re-index your site. You should make all
// setting changes directly from the Indexer, via the Configuration window.
// 
// If you wish to modify the text messages such as "Search results for...",
// etc. then look up "Zoom Language Files" or "Translating the search page"
// in the Users Guide for information.

var UseUTF8 = 0;
var Charset = "windows-1252";
var NoCharset = 0;
var MapAccents = 0;
var MinWordLen = 2;
var Highlighting = 0;
var GotoHighlight = 0;
var PdfHighlight = 1;
var TemplateFilename = "search_template.html";
var FormFormat = 1;
var Logging = 0;
var LogFileName = "./logs/searchwords.log";
var MaxKeyWordLineLen = 256;
var DictIDLen = 2;
var NumKeywords = 7308;
var NumPages = 115;
var MaxMatches = 1000;
var MaxContextSeeks = 500;
var DictReservedLimit = 165;
var DictReservedSuffixes = 83;
var DictReservedPrefixes = 124;
var DictReservedNoSpaces = 165;
var WordSplit = 1;
var ZoomInfo = 0;
var Timing = 0;
var DefaultToAnd = 0;
var SearchAsSubstring = 0;
var ToLowerSearchWords = 1;
var StripDiacritics = 0;
var ContextSize = 30;
var MaxContextKeywords = 3;
var AllowExactPhrase = 0;
var UseLinkTarget = 0;
var UseDateTime = 0;
var UseZoomImage = 0;
var WordJoinChars = ".-_'";
var Spelling = 0;
var Recommended = 0;
var NumRecommended = 0;
var RecommendedMax = 0;
var UseCats = 0;
var SearchMultiCats = 0;
var DisplayNumber = 0;
var DisplayTitle = 1;
var DisplayMetaDesc = 1;
var DisplayContext = 0;
var DisplayTerms = 0;
var DisplayScore = 0;
var DisplayURL = 0;
var DisplayDate = 0;
var DisplayFilesize = 0;
var Version = "Version 5.1 (1017) PRO";
