pageinfo = [[1528845397,973],
	[1528845397,1366],
	[1531152315,3287],
	[1528845397,3321],
	[1528845397,6697],
	[1532640965,204715],
	[1528845397,3517],
	[1528845397,2039],
	[1528845397,765],
	[1528845397,3751],
	[1528845397,15962],
	[1528845397,1139],
	[1528845397,14340],
	[1528845397,22179],
	[1528845397,159727],
	[1528845397,139735],
	[1528845397,25845],
	[1528845397,3272],
	[1528845397,2114],
	[1528845397,4128],
	[1532640965,5399],
	[1532640965,7465],
	[1528845397,5931],
	[1528845397,15394],
	[1528845397,4960],
	[1528845397,15155],
	[1528845397,5335],
	[1528845397,4385],
	[1528845397,3059],
	[1532467658,7963],
	[1529711896,27242],
	[1528845397,2354],
	[1532467658,19302],
	[1532559326,20259],
	[1532467658,52652],
	[1528845397,2187],
	[1532467658,9395],
	[1528845397,25144],
	[1532467658,173981],
	[1528845398,2537],
	[1528845398,812],
	[1528845398,1876],
	[1532640965,10522],
	[1528845397,7780],
	[1528845398,406],
	[1532467659,8147],
	[1528845398,5750],
	[1532467659,1472],
	[1528845398,6489],
	[1532559326,118818],
	[1532559326,128997],
	[1528845398,10071],
	[1528845398,910],
	[1528845398,4649],
	[1532640965,21675],
	[1528845398,1952],
	[1532640965,11509],
	[1528845398,1016],
	[1528845398,1829],
	[1528845398,40908],
	[1528845398,28607],
	[1528845398,27141],
	[1528845398,9053],
	[1528845398,12228],
	[1528845398,52293],
	[1528845398,14141],
	[1528845398,4016],
	[1528845398,46565],
	[1528845398,2013],
	[1528845398,14875],
	[1528845398,4297],
	[1528845398,4841],
	[1528845398,4523],
	[1532537586,11925],
	[1532537586,20302],
	[1528845397,9321],
	[1528845398,2023],
	[1532467659,11085],
	[1528845398,727],
	[1528845398,69],
	[1528845398,65],
	[1528845398,65],
	[1528845398,1969],
	[1528845398,3050],
	[1528845398,1827],
	[1528845398,1775],
	[1528845398,1511],
	[1528845398,4835],
	[1528845398,3303],
	[1528845398,2402],
	[1528845398,2373],
	[1528845398,9578],
	[1528845398,8713],
	[1528845398,3196],
	[1528845398,10820],
	[1528845398,3531],
	[1528845398,8517],
	[1528845398,540],
	[1532639266,1854],
	[1528845398,14363],
	[1532559326,23392],
	[1528845399,5055],
	[1532467659,1400],
	[1528845399,920],
	[1528845399,3808],
	[1528845399,2866],
	[1532469546,17585],
	[1528845399,2858],
	[1528845399,4631],
	[1532469522,13846],
	[1528845399,5936],
	[1528845399,4945],
	[1528845399,3710],
	[1532550026,4848],
	[1528845399,2580]];
pagedata = [ ["about2.htm","About","Using the Help Files The help files are designed to familiarize users with the Cisco Packet Tracer interface, functions, and features. Although th...",""],
["accounts.htm","Accounts","Accounts Packet Tracer requires a valid Cisco Networking Academy login for unrestricted use. Without a valid account, Packet Tracer can still be u...",""],
["acknowledgements.htm","Acknowledgments","?Packet Tracer 7.2 Development Team Original Packet Tracer Concept and Design Dennis Frezzo Michael Wang Mark Chen Brad Anderson Development Team ...",""],
["activityWizard.htm","Activity Wizard","Activity Wizard The Activity Wizard is an assessment tool that allows you to create highly specific networking scenarios for other users. You can ...",""],
["activityWizard_answerNetwork.htm","Answer Network","Answer Network In the Answer Network panel, you construct the answer network, and mark the elements of the network on which you want to assess the...",""],
["activityWizard_assessmentItems.htm","Assessment Items","Assessment Items What are Assessment Items? The assessment items are found in the Assessment Items tab of the Answer Network section in the Activi...",""],
["activityWizard_initialNetwork.htm","Initial Network","Initial Network In the Initial Network panel, you set the network from which the user will start the activity. One option for setting up the initi...",""],
["activityWizard_instructions.htm","Instructions","Instructions The student instructions for the activity are entered in the Instructions panel. When students open the activity file, the instructio...",""],
["activityWizard_password.htm","Password","Password The Password panel allows you to set a password for the Activity Wizard features of the activity file. If no password is set, anyone who ...",""],
["activityWizard_run.htm","Running Activity Files","Running Activity Files You start an activity by opening a saved activity (.pka) file. You will first see the Instructions window telling you how t...",""],
["activityWizard_scoringModelAndScripting.htm","Scoring Model/Scripting","Scoring Model/Scripting The Scoring Model is an Evidence Centered Design process by which to assess work products through the application of scori...",""],
["activityWizard_test.htm","Testing/Checking the Activity (Previewing)","Testing/Checking the Activity (Previewing) When you choose the Test Activity tab from the Activity Menu, you can do a trial run of the activity yo...",""],
["activityWizard_variableManager.htm","Variable Manager","Variable Manager The Variable Manager provides the ability for an activity author to add dynamic capabilities into an activity. These capabilities...",""],
["CLI_asa.htm","Supported Commands: ASA","ASA Packet Tracer uses a simplified model of the Cisco Adaptive Security Appliance Software. Click on the CLI tab in the ASA configuration window ...",""],
["CLI_routerIOS.htm","Cisco IOS Supported Commands: Routers","Routers: IOS Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the router configuration window to access the Cisco I...",""],
["CLI_routerIOS15.htm","Cisco IOS 15 Supported Commands: Routers","Routers: IOS 15 Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the router configuration window to access the Cisc...",""],
["CLI_switchIOS.htm","Cisco IOS Supported Commands: Switches","Switches: IOS Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the switch configuration window to access the Cisco ...",""],
["configuringDevices.htm","Configuring Devices","Configuring Devices As with real networks, the networks you make in Packet Tracer must be properly configured before they \"work.\" For simple devic...",""],
["config_asa.htm","Configuring ASA","Configuring ASA The Config tab for the ASA offers four general levels of configuration: global, clientless vpn, switching, and interface. The glob...",""],
["config_clouds.htm","Configuring Clouds","Configuring Clouds The Config tab offers three general levels of configuration: global, connections, and interface. To configure at the global lev...",""],
["config_HomeRouter.htm","Configuring Tri-Band Home Router","Configuring Tri-Band Wireless Home Router The Config tab offers two general levels of configuration: global and interface. To configure at the glo...",""],
["config_MerakiDevices.htm","Configuring Tri-Band Home Router","Configuring Meraki Devices Cisco Packet Tracer supports a simplified version of the Meraki Security Appliance (SA), MX65W, and a cloud based Merak...",""],
["config_others.htm","Configuring Other Devices","Configuring Other Devices The configuration options for all other devices are relatively simple. In general, you can change their display names in...",""],
["config_PCs.htm","Configuring PCs","Configuring PCs, Laptops, Tablet PCs, and PDAs You can configure the global settings and interface settings on the PC, laptop, tablet PC, and PDA ...",""],
["config_routers.htm","Configuring Routers","Configuring Routers The Config tab offers four general levels of configuration: global, routing, switching (Cisco 1841 and Cisco 2811 only), and i...",""],
["config_servers.htm","Configuring Servers","Configuring Servers The Config tab offers two levels of configuration: global, and interface. To configure at the global level, click the GLOBAL b...",""],
["config_switches.htm","Configuring Switches","Configuring Switches The Config tab for the switch offers three general levels of configuration: global, switching, and interface. The global leve...",""],
["config_WLCs.htm","Configuring Wireless LAN Controllers","Configuring Wireless LAN Controllers The Config tab of the Wireless LAN Controller (WLC) offers two general levels of configuration: global and in...",""],
["config_wrt300n.htm","Configuring WRT300N","Configuring WRT300N The Config tab offers two general levels of configuration: global and interface. To configure at the global level, click the G...",""],
["connectionsLinks.htm","Connections / Links","Connections / Links Packet Tracer supports a wide range of network connections. Each cable type can only be connected to certain interface types. ...",""],
["copyrights.htm","No title","Cisco Packet Tracer Software License Agreement IMPORTANT: PLEASE READ THIS CISCO PACKET TRACER SOFTWARE LICENSE AGREEMENT (THE &#8220;AGREEMENT&#8221;) CAREFU...",""],
["devicesAndModules.htm","Devices and Modules","Devices and Modules Packet Tracer supports a wide array of modules for networking devices. To change a module in any device, you must first turn o...",""],
["devicesAndModules_endDevices.htm","Devices and Modules: End Devices","Devices and Modules: End Devices All images on this page are thumbnails in which you can click to bring up a larger image. PC-PT The PC-PT provide...",""],
["devicesAndModules_others.htm","Devices and Modules: Other Devices","Devices and Modules: Other Devices All images on this page are thumbnails on which you can click to bring up a larger image. Hub-PT The Hub-PT pro...",""],
["devicesAndModules_routers.htm","Devices and Modules: Routers","Devices and Modules: Routers All images on this page are thumbnails on which you can click to bring up a larger image. Router: 4321 The Cisco 4000...",""],
["devicesAndModules_structuredCabling.htm","Devices and Modules: Other Devices","Devices and Modules: Structured Cabling Devices Structured Cabling Devices are a special class of devices that are only visible in Physical View. ...",""],
["devicesAndModules_switches.htm","Devices and Modules: Switches","Devices and Modules: Switches All images on this page are thumbnails on which you can click to bring up a larger image. Switch: 2960-24TT The Cisc...",""],
["environment.htm","Environment","Environment The intercity, city, buildings, wiring closets, and generic containers all have an environment. There are a couple dozen default envir...",""],
["faqTroubleShoot.htm","Frequently Asked Questions (FAQ)/Troubleshoot Guide","Frequently Asked Questions (FAQ)/Troubleshooting Guide Topics General Specific Protocol Modeling Internet of Things General Issues 1. My computer ...",""],
["fontPreference.htm","Font Setting and 4k Support","Font Setting and 4k Support Font preference User can adjust font size, family and color for different application User Interfaces (UI), there are ...",""],
["gettingStarted.htm","Getting Started","Getting Started The best place to get started is to review the help files. The help files contain comprehensive documentation on almost all the fe...",""],
["guest_login.htm","Guest Login","Guest Login Packet Tracer requires a valid Cisco Networking Academy login for unrestricted use. Without a valid account, Packet Tracer can be used...",""],
["GUI_HomeRouter.htm","Tri-Band Home Router: GUI","Tri-Band Home Router: GUI The GUI tab offers the same configurations and settings as the Config tab with some additional features for access restr...",""],
["GUI_wrt300n.htm","WRT300N: GUI","WRT300N: GUI The GUI tab offers the same configurations and settings as the Config tab with some additional features for access restrictions, port...",""],
["index.htm","Cisco Packet Tracer Help","",""],
["interfaceOverview.htm","Interface Overview","Interface Overview When you open Packet Tracer, by default you will be presented with the following interface: This initial interface contains ten...",""],
["intro.htm","Introduction","Introduction Welcome to Cisco Packet Tracer. Packet Tracer is a medium fidelity, network-capable, simulation-based learning environment for networ...",""],
["iot.htm","Internet of Things","Internet of Things Included in this version of Packet Tracer are a variety of networked physical objects or Things. There are Smart Things that ar...",""],
["iot_creating_things.htm","Creating Things","Creating Things All Things, Smart Things and Components in Packet Tracer use the same base device: Thing. What makes them unique is the configurat...",""],
["iot_javascript_api.htm","JavaScript API","JavaScript API Program Structure and Events Function Return Type Description Example setup() N/A If defined, this function is called once when the...",""],
["iot_python_api.htm","Python API","Python API Program Structure and Events Package = N/A Function Return Type Description Example cleanUp() N/A If defined, this function is called o...",""],
["iot_using_things.htm","Using Things","Using Things Where are the Things? In addition to routers and switches, the Network Component Box now contains a variety of Smart Things and compo...",""],
["iot_visual_api.htm","Visual API","Visual API In addition to JavaScript and Python, Packet Tracer supports programming using a WYSIWYG interface based on Blockly. All the supported ...",""],
["ipc.htm","IPC","IPC (Inter-Process Communication) The IPC (Inter-Process Communication) feature controls an external programming extension for Packet Tracer that ...",""],
["keyboardShortcuts.htm","Keyboard Shortcuts","Keyboard Shortcuts Many actions in Packet Tracer are keyboard-accessible for your convenience. In addition to key combinations, the following keys...",""],
["login.htm","Login","Login Packet Tracer requires a valid Cisco Networking Academy login for unrestricted use. Without a valid account, Packet Tracer will limit the nu...",""],
["menu.htm","Main Menu","Packet Tracer Search Introduction What&#39;s New Program Usage Accounts Logging In Guest Login Getting Started Interface Overview Preferences User Pro...",""],
["modeling.htm","Modeling in Packet Tracer","Modeling in Packet Tracer Packet Tracer simulates the behavior of real networks and devices using models. As with all simulations, the program is ...",""],
["model_layer1.htm","Layer 1 Models","Layer 1 Models How hubs process frames When a hub receives a frame ( flowchart here): If two or more ports receive frames at the same time, a coll...",""],
["model_layer2.htm","Layer 2 Models","Layer 2 Models How switches process incoming frames When a switch receives a frame ( flowchart here): It compares the receiving port&#39;s type (trunk...",""],
["model_layer3IP.htm","Layer 3 IP Models","Layer 3 IP Models How IP and IPv6 are modeled Packet Tracer models only certain aspects of IP. IP version 4 is modeled. IP addresses are 32 bits l...",""],
["model_layer3Routing.htm","Layer 3 Routing Models","Layer 3 Routing Models - RIPv1 RIPv2 EIGRP OSPF How a router starts the RIP process The router generates a RIP request packet to be sent out all p...",""],
["model_layer4.htm","Layer 4 Models","Layer 4 Models How devices process UDP segments This procedure explains how a device sends and receives UDP segments. When the device receives a s...",""],
["model_layer5.htm","Layer 5 Models","Layer 5 Models How Routers Handle ISAKMP Segments When a router sends an ISAKMP segment ( flowchart here): If a packet is getting out of the devic...",""],
["model_layer7.htm","Layer 7 Models","Layer 7 Models How DHCP clients work DHCP client sends a DHCP-DISCOVER packet ( flowchart here): When a DHCP client device receives a packet: It d...",""],
["model_misc.htm","Other Models","Other Models How routers process incoming packets (NAT process) When a router receives a packet: It checks if the receiving port is a NAT outside ...",""],
["mode_realtime.htm","Realtime Mode","Realtime Mode In Realtime Mode, your network is always running (like a real network) whether you are working on the network or not. Your configura...",""],
["mode_simulation.htm","Simulation Mode","Simulation Mode In Simulation Mode, you can watch your network run at a slower pace, observing the paths that packets take and inspecting them in ...",""],
["mode_simulation_complexPDUs.htm","Simulation Mode: Complex PDUs","Simulation Mode: Complex PDUs In addition to simple, quick pings, you can also send customized PDUs. In the Common Tools Bar, click the Add Comple...",""],
["mode_simulation_PDUcolor.htm","PDU Color Legend","PDU Color Legend PDU Type Hex Value Actual Color AAA Radius Client Process 0xedd170 AAA Radius Server Process 0xedd170 AAA Tacacs Client Process 0...",""],
["mode_simulation_PDUinfo.htm","Simulation Mode: PDU Information","Simulation Mode: PDU Information During a simulation, you can click on a packet (on the topology or the corresponding event in the Event List) to ...",""],
["mode_simulation_Scenarios.htm","Simulation Mode: Managing Simulation Scenarios","Simulation Mode: Managing Simulation Scenarios In Packet Tracer, you can set up and simulate complex networking situations (scenarios) through the...",""],
["mode_simulation_specialNotes.htm","Simulation Mode: Special Notes","Simulation Mode: Special Notes Editing the Network and Using the Cisco IOS in Simulation Mode Although Realtime Mode is the preferred mode for net...",""],
["multiuser.htm","Multiuser","Multiuser Multiuser communication allows multiple point-to-point (peer) connections between multiple instances of Packet Tracer. By allowing commu...",""],
["myFirstPTLab.htm","My First Packet Tracer Lab","? My First Packet Tracer Lab Introduction Welcome to Packet Tracer. Research has shown that users who master a few basic tasks when first starting...",""],
["OpenSSL_License.htm","OpenSSL Liscense","OpenSSL License License Issues The OpenSSL toolkit stays under a dual license, i.e. both the conditions of the OpenSSL License and the original SS...",""],
["operatingModes.htm","Operating Modes","Operating Modes Packet Tracer operating modes reflect the network time scheme. In Realtime Mode, your network runs in a model of real time, within...",""],
["preferences.htm","Settings and Preferences","Settings and Preferences Preferences You can customize your Packet Tracer experience by setting your own preferences. From the Menu Bar, select Op...",""],
["programming.htm","Programming","Programming Programming is the logic that makes the devices function. Packet Tracer supports three different scripting languages: Javascript, Pyth...",""],
["programming_javascript.htm","No title","",""],
["programming_python.htm","No title","",""],
["programming_visual.htm","No title","",""],
["sampleFilesAndDesignPatterns.htm","Sample Files, File Compatibility, and Design Patterns","Sample Files, File Compatibility, and Design Patterns There are over 300 Packet Tracer .pka files that exist embedded in the Discovery and Explora...",""],
["sampleFilesAndDesignPatterns_conceptBuilder.htm","Concept Builders","Concept Builders Concept builders are model-building inquiries and investigations leading to student-created explanations and animations of networ...",""],
["sampleFilesAndDesignPatterns_design.htm","Design Challenges","Design Challenges Design challenges are constraint-based problems with multiple correct solutions. They may range from very simple (devise a class...",""],
["sampleFilesAndDesignPatterns_skillBuilder.htm","Skill Builders","Skill Builders Skill builders support algorithmic problem solving in support of the development of networking procedural knowledge. For example, s...",""],
["sampleFilesAndDesignPatterns_troubleshoot.htm","Troubleshooting","Troubleshooting Troubleshooting activities include diagnosing, isolating, and fixing the simulated network from a previously bugged network file. ...",""],
["scriptModules.htm","Script Modules","Script Modules Script Modules are independent entities that add new functionality to Packet Tracer similar to External Applications (ExApps). But ...",""],
["scriptModules_customUdp.htm","Script Modules","Script Modules - Custom UDP Processes With Script Modules, instructors and students can now develop and add new protocols to PT. They are called c...",""],
["scriptModules_dataStore.htm","Script Modules","Script Modules - Data Store The data store is the other part of the model in the Script Module. The data store has a list of data files, in json, ...",""],
["scriptModules_data_store_editor.htm","DataStore Editor","Data Store Editor Besides using the Data Store Tab that was mentioned in Script Modules - Data Store , Packet Tracer also allows users to edit the...",""],
["scriptModules_scriptEngine.htm","Script Modules","Script Modules - Script Engine Each Script Module has one instance of a Qt Script Engine. A Script Module can contain multiple script files writte...",""],
["scriptModules_scriptingInterface.htm","Script Modules","Script Modules - Scripting Interface The Scripting Interface is the Script Module development environment inside PT. This is extended from the Scr...",""],
["scriptModules_tips.htm","Script Modules","Script Modules - Tips The dprint() function is per Script Module. Check the Debug Dialog of the correct Script Module for these outputs. Changes m...",""],
["scriptModules_webViews.htm","Script Modules","Script Modules - Web Views Web Views Web views are using the QtWebKit functionality to render HTML5. Script Modules use web views to create custom...",""],
["search.html","Search","Search Enter keyword(s) to search. ",""],
["shapetest.htm","Shape Tests","Shape Test Students can draw around a feature in the network that can be scored in the Activity Wizard Shape Tests is an activity feature in Packe...",""],
["support.htm","Packet Tracer Support and Contact Information","Packet Tracer Support and Contact Information Please contact the Academy Help Desk, or report a Packet Tracer bug by clicking on \"Help &#166; Report an...",""],
["systemRequirements.htm","System Requirements","System Requirements Minimum CPU: Intel Pentium 4, 2.53 GHz or equivalent OS: Microsoft Windows 7, Microsoft Windows 8.1, Microsoft Windows 10 or U...",""],
["timeConstants.htm","Time Constants","Time Constants Packet Tracer uses the following time constants: RIP/RIPv6 default update 30 secs RIP/RIPv6 default timeout 3 mins RIP/RIPv6 defaul...",""],
["translation.htm","Packet Tracer Translation Process","Packet Tracer Translation Process Packet Tracer supports semi-automated translation to all Unicode-supported languages. The first part of this gui...",""],
["usesForPT.htm","Uses for Packet Tracer","Uses for Packet Tracer For Students Welcome to the world of computer networking. Packet Tracer can be a fun, take-home, flexible piece of software...",""],
["whatsNew.htm","What&#39;s New","What&#39;s New Users of previous versions of Packet Tracer will note a variety of new features in this version of Packet Tracer. Workspace New themes ...",""],
["workspaceBasics.htm","The Logical and Physical Workspaces","The Logical and Physical Workspaces Packet Tracer uses two representation schemes for your network: the Logical Workspace and the Physical Workspa...",""],
["workspacelist.htm","Workspace List","Workspace List This view provides a list style representation of the current visible logical workspace. In situations where keyboard navigation an...",""],
["workspaceViewport.htm","Workspace Viewports","Workspace Viewport Panels Workspace Viewport Panel (Viewport in short) is a panel showing a part or the entire workspace area. This panel is espec...",""],
["workspace_logical.htm","The Logical Workspace","The Logical Workspace The Logical Workspace is where you will spend the majority of your time building and configuring your network. In conjunctio...",""],
["workspace_logical_creating_custom_templates.htm","Creating Custom Templates","Creating Custom Templates Creating Custom Templates The Device Template Manager allows you to save devices, clusters, and physical containers as t...",""],
["workspace_logical_customIconsAndBG.htm","The Physical Workspace: Moving Devices","Customizing Icons and Backgrounds (BG) Using Custom Icons Icons that represent devices in Packet Tracer in both Logical and Physical mode can now ...",""],
["workspace_physical.htm","The Physical Workspace","The Physical Workspace The purpose of the Physical Workspace is to give a physical dimension to your logical network topology. It gives you a sens...",""],
["workspace_physical_cableManipulation.htm","The Physical Workspace: Cable Manipulation","The Physical Workspace: Cable Manipulation In Physical Workspace, cables can be manipulated to provide a more realistic representation of a physic...",""],
["workspace_physical_customIconsAndBG.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Customizing Icons and Backgrounds (BG) Using Custom Icons Icons that represent devices in Packet Tracer in both Logical an...",""],
["workspace_physical_distanceMeasurements.htm","The Physical Workspace: Distance Measurements","The Physical Workspace: Distance Measurements The Physical Workspace provides the dimension of distance to Ethernet and wireless devices. This dis...",""],
["workspace_physical_movingDevices.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Moving Devices The Physical Workspace allows you to move your devices to various locations. To move devices up or down the...",""],
["workspace_physical_specialNotes.htm","The Physical Workspace: Special Notes","The Physical Workspace: Special Notes Navigation Panel You can click on the Navigation button from the Physical Workspace Bar to bring up the navi...",""]];
